services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: vambe-db
    networks:
      - vambe-network
    restart: unless-stopped


  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vambe-api
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    volumes:
      - ./api:/src/app
      - /src/app/node_modules
    networks:
      - vambe-network

volumes:
  postgres_data:

networks:
  vambe-network:
    driver: bridge
