name: Docker Compose CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env file from secret
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: Stop running containers
      run: docker compose down

    - name: Build and start containers
      run: docker compose up --build -d
